### ISSUE TITLE
能否说一下线路是什么

### ISSUE THREAD

**Issue by dzhuang** [ZhiXuanWang/cf-speed-dns#1]
相同的ip，联通和移动的使用体验会差很远吧，感谢

**Comment by ZhiXuanWang** [comment]
杭州 电信

**Comment by dzhuang** [comment]
收到，谢谢！

**Comment by cy920820** [comment]
@ZhiXuanWang 请问大佬，这个的原理是什么？ 能否可以适配其他运营商的线路，另外配置中的 SECRETID  SECRETKEY  分别代表什么呢？

**Comment by ZhiXuanWang** [comment]
> @ZhiXuanWang请问大佬，这个原理是什么？能否配置其他运营商的线路，另外中的 SECRETID SECRETKEY 分别代表什么格式？

原理：杭州电信家用宽带，使用CloudflareSpeedTest获取优选ip，分享给大家。使用github静态页。
获取：SECRETID SECRETKEY ，在腾讯云获取，https://blog.csdn.net/Susan003/article/details/125914027。本质是将ip解析到域名上，不用手动换ip。
