### ISSUE TITLE
dnscf报错，大佬能帮忙看看原因吗，action的值都设置了

### ISSUE THREAD

**Issue by ypq123456789** [ZhiXuanWang/cf-speed-dns#12]
Run python dnscf.py
Error fetching DNS records: {"success":false,"errors":[{"code":10000,"message":"Authentication error"}]}

Traceback (most recent call last):
  File "dnscf.py", line 101, in <module>
    main()
  File "dnscf.py", line 95, in main
    dns = update_dns_record(dns_records[index], CF_DNS_NAME, ip_address)
TypeError: 'NoneType' object is not subscriptable
Error: Process completed with exit code 1.

**Comment by ZhiXuanWang** [comment]
手动先创建2条记录试试
