### ISSUE TITLE
IP停止更新了

### ISSUE THREAD

**Issue by jihu9** [ZhiXuanWang/cf-speed-dns#2]
大佬好，昨天开始ip停止更新了，请问后面还会维护吗？

**Comment by ZhiXuanWang** [comment]
本地网络被绊，ssh: connect to host github.com port 22: Connection timed out，正在找解决方案。

**Comment by ZhiXuanWang** [comment]
已恢复，使用git官网解决办法：https://docs.github.com/en/authentication/troubleshooting-ssh/using-ssh-over-the-https-port，ssh 443 端口
