### ISSUE TITLE
没有DNSCF实时域名解析推送

### ISSUE THREAD

**Issue by Jacobax** [ZhiXuanWang/cf-speed-dns#5]
添加了`CF_API_TOKEN`（写DNS）、`CF_ZONE_ID`（我的域名623057.xyz下的ID）、`CF_DNS_NAME`（dns.623057.xyz）这3个secrets，`PUSHPLUS_TOKEN`这个推送的没添加
action成功，dns.623057.xyz下没有IP
请求解惑指导

**Comment by ZhiXuanWang** [comment]
![39e7b00490162a2db35ccfa2b21e5892](https://github.com/ZhiXuanWang/cf-speed-dns/assets/8485571/bf15583d-323f-4b00-9e42-7d3b7eeb8193)
查看 action 运行日志，解决。

**Comment by ZhiXuanWang** [comment]
<img width="957" alt="image" src="https://github.com/ZhiXuanWang/cf-speed-dns/assets/8485571/4802fafc-0dad-45c5-a329-011f17d61a47">
手工添加2条记录，重跑试试。

**Comment by Jacobax** [comment]
> ![39e7b00490162a2db35ccfa2b21e5892](https://github.com/ZhiXuanWang/cf-speed-dns/assets/8485571/bf15583d-323f-4b00-9e42-7d3b7eeb8193)
> 查看 action 运行日志，解决。 

看了下，actions只跑了static_page.yml，没跑dns_cf.yml，不知道有没有哪做错或没做  
![两个都试过.jpg](https://github.com/ZhiXuanWang/cf-speed-dns/assets/23228895/f2cbf31d-ac53-421b-93a8-2aeb23ec500d)

![Screenshot_2024-02-25-18-43-03-621_com.brave.browser_beta-edit.jpg](https://github.com/ZhiXuanWang/cf-speed-dns/assets/23228895/b0a0d261-9833-4894-ab38-9aee769bced3)

![Screenshot_2024-02-25-18-42-04-128_com.brave.browser_beta-edit.jpg](https://github.com/ZhiXuanWang/cf-speed-dns/assets/23228895/82b540df-2a38-4c73-ab10-4dcc99a67e84)

**Comment by ZhiXuanWang** [comment]
<img width="1319" alt="image" src="https://github.com/ZhiXuanWang/cf-speed-dns/assets/8485571/df929c9b-5976-4a6d-a81f-1f19e2f91316">
提示的很清楚，打开它。

**Comment by Jacobax** [comment]
是我看漏了，感谢大佬的作品和指导
