### ISSUE TITLE
为什么我的网站不更新

### ISSUE THREAD

**Issue by xinkeji** [ZhiXuanWang/cf-speed-dns#6]
网站一直数据一直没动

**Comment by ZhiXuanWang** [comment]
你的网站？

**Comment by xinkeji** [comment]
就iptop这个文件也不动

**Comment by ZhiXuanWang** [comment]
Actions 页面启用 Workflows，并启用 Upstream Sync Action。

**Comment by xinkeji** [comment]
好像不行

**Comment by ZhiXuanWang** [comment]
> 好像不行

自己研究下吧，为了证明行不行，fork项目测试了，是行的哦。
https://github.com/105570577/cf-speed-dns/actions/runs/8149885917/job/22275245113

**Comment by ZhiXuanWang** [comment]
![image](https://github.com/ZhiXuanWang/cf-speed-dns/assets/8485571/315d5fcf-43a7-4ca0-99e2-c7e3fb579c7c)
![image](https://github.com/ZhiXuanWang/cf-speed-dns/assets/8485571/c4c091f8-1d6b-4e98-87d7-e0be6485e3c9)

**Comment by xinkeji** [comment]
你这个不也是只更新了一次吗

**Comment by ZhiXuanWang** [comment]
> 你这个不也是只更新了一次吗

on:
  schedule:
    - cron: "0 0 * * *" # every day
  workflow_dispatch:

修改 cron 调频。

不要再继续问了，巨婴，无任何探索自主学习能力。issues 关闭了。

**Comment by xinkeji** [comment]
对不起



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月6日(周三) 上午9:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ZhiXuanWang/cf-speed-dns] 为什么我的网站不更新 (Issue #6)




  
你这个不也是只更新了一次吗
  
on:
 schedule:
 - cron: "0 0 * * *" # every day
 workflow_dispatch:
 
修改 cron 调频。
 
不要再继续问了，巨婴，无任何探索自主学习能力。issues 关闭了。

**Comment by ZhiXuanWang** [comment]
> 对不起
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年3月6日(周三) 上午9:45 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [ZhiXuanWang/cf-speed-dns] 为什么我的网站不更新 (Issue #6) 你这个不也是只更新了一次吗 on: schedule: - cron: "0 0 * * *" # every day workflow_dispatch: 修改 cron 调频。 不要再继续问了，巨婴，无任何探索自主学习能力。issues 关闭了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

兄弟，也跟你说声抱歉，刚才言语有点过激。恨铁不成钢，良苦用心忘理解。

**Comment by xinkeji** [comment]
没事没事，可能我真不太适合



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月6日(周三) 中午11:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ZhiXuanWang/cf-speed-dns] 为什么我的网站不更新 (Issue #6)




  
对不起
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年3月6日(周三) 上午9:45 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [ZhiXuanWang/cf-speed-dns] 为什么我的网站不更新 (Issue #6) 你这个不也是只更新了一次吗 on: schedule: - cron: "0 0 * * " # every day workflow_dispatch: 修改 cron 调频。 不要再继续问了，巨婴，无任何探索自主学习能力。issues 关闭了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.**&gt;
  
兄弟，也跟你说声抱歉，刚才言语有点过激。恨铁不成钢，良苦用心忘理解。
